export const BOOKING_MANAGEMENT_TEXT = {
  title: "Booking Management",
  houseCleanerLabel: "House Cleaner",
  repairExpertLabel: "Repair Expert",
  expertSuffix: " Expert",
  viewDetailsBtn: "View Details",
  callExpertAria: "Call expert",
  noPhoneAria: "No phone number available",
  tableHeaderUser: "User",
  tableHeaderMobileNumber: "Mobile Number",
  tableHeaderEmail: "Email",
  tableHeaderBookedServices: "Booked Services",
  tableHeaderAddress: "Address",
  tableHeaderAmount: "Amount",
  tableHeaderPaymentMethod: "Payment Method",
  detailsTableNoBookings: "No service bookings for this customer",
  detailsHeaderServiceID: "Service ID",
  detailsHeaderService: "Service",
  detailsHeaderServiceType: "Service Type",
  detailsHeaderDateTime: "Date & Time",
  detailsHeaderAssignedExpert: "Assigned Expert",
  detailsHeaderStatus: "Status",
  filterTitle: "Filter",
  filterServiceType: "Service Type",
  filterDate: "Date",
  filterTime: "Time",
  filterBookedServices: "Booked Services",
  filterAmount: "Amount",
  filterPaymentMethod: "Payment Method",
  filterStatus: "Status",
  filterAllOption: "All",
  filterDoneBtn: "Done",
  failedToLoadFilters: "Failed to load filter options",
};
