export const CONTACT_TEXT = {
  successMessage: "Message sent successfully!",
  heroTitle: "Contact Us",
  phoneNumber: "+1 (555) 123-4567",
  emailAddress: "example.email@domain.com",
  addressLine1: "1234 Elm Street, Apt 567,",
  addressLine2: "Springfield, IL 62704,",
  addressLine3: "United States",
  formTitle: "Get in Touch",
  formSubtitle: "Send a message",
  firstNameLabel: "First Name",
  lastNameLabel: "Last Name",
  mobileLabel: "Mobile Number",
  emailLabel: "Email",
  descriptionLabel: "Description",
  sendingBtn: "Sending Message...",
  sendBtn: "Send Message",
  failedToSendMessage: "Failed to send message:",
};
