export const HOME_TEXT = {
  heroTitle: "Home services at your doorstep",
  heroSubtitle: "Your one-stop destination for home care.",
  statCustomersValue: "5M+",
  statCustomersLabel: "Customers Globally",
  statServicesValue: "500+",
  statServicesLabel: "Services",
  searchPlaceholder: "Search for \u201cAc Cleaning Service\u201d",
  searchBtn: "Search",
  searching: "Searching\u2026",
  noResults: "No results",
  categoriesTitle: "What are you looking for?",
  popularServicesTitle: "Popular Services",
  allServicesTitle: "All Services",
  searchResultsTitle: "Search results for",
  seeMoreBtn: "See More",
  joinUsTitle: "Want to Join Us?",
  joinUsSubtitle: "Become a service partner and Join",
  joinUsSuffix: "partners across India.",
  joinNowBtn: "Join Now",
  partnerCount: "40,000+",
};
