export const OFFERS_TEXT = {
  pageTitle: "Offers",
  filterTitle: "Filter",
  couponDiscountFilter: "Coupon Discount (%)",
  couponAppliedFilter: "Coupon Applied",
  availabilityFilter: "Availability",
  addBtn: "Add",
  editCouponTitle: "Edit Coupon",
  addCouponTitle: "Add Coupon",
  couponCodeLabel: "Coupon Code",
  couponDescLabel: "Coupon Description",
  couponDiscountLabel: "Coupon Discount",
  couponUsageLimit: "Usage Limit",
  statusLabel: "Status",
  activeOption: "Active",
  inactiveOption: "Inactive",
  confirmDeleteTitle: "Confirm Delete",
  deleteBtn: "Delete",
  deleteWarningMsg: "This action cannot be undone. Are you sure you want to delete",
  couponCodeHeader: "Coupon Code",
  couponDescHeader: "Coupon Description",
  couponDiscountHeader: "Coupon Discount",
  couponAppliedHeader: "Coupon Applied",
  statusHeader: "Status",
  actionHeader: "Action",
  errorFetchingCoupons: "Error fetching coupons:",
  cancelBtn: "Cancel",
  submitBtn: "Submit",
  discountPercentage: "Percentage",
  discountFixed: "Fixed Amount",
  loadingText: "Loading...",
  doneBtn: "Done",
  resetBtn: "Reset",
  maxUsageLabel: "Max Usage",
};
