export const PROFILE_TEXT = {
  title: "My Profile",
  fetchProfileError: "Fetch profile error:",
  contactInfoTitle: "Contact Information",
  savedAddressesTitle: "Saved Addresses",
  personalInfoTitle: "Personal Information",
  genderLabel: "Gender",
  dobLabel: "DOB",
  firstNameLabel: "First Name",
  lastNameLabel: "Last Name",
  mobileLabel: "Mobile Number",
  emailLabel: "Email Address",
  updateProfileSuccess: "Profile updated successfully!",
  updateProfileError: "Failed to update profile",
  addressDeleteSuccess: "Address deleted successfully!",
  addressDeleteError: "Failed to delete address",
  addressAddSuccess: "Address added successfully!",
  addressAddError: "Failed to add address",
  addressUpdateSuccess: "Address updated successfully!",
  addressUpdateError: "Failed to update address",
  addBtn: "Add",
  noSavedAddresses: "No saved addresses found.",
};
