export const SERVICE_PARTNER_TEXT = {
  thankYouMessage: "Thank you for applying to NestAssist!",
  reviewNotification: "We'll review your application and get back to you soon.",
  viewServicesBtn: "View Services",
  goToHomeBtn: "Go to Home",
  fillDetailsHeading: "Fill Out Below Details to Join Us",
  profileImage: "Profile Image",
  uploadBtn: "Upload",
  successSubmit: "Application submitted successfully!",
  personalInfoHeading: "Personal Information",
  educationInfoHeading: "Educational Information",
  professionalInfoHeading: "Professional Information",
  skillsExpertiseHeading: "Skills & Expertise",
  servicesOfferedHeading: "Services Offered",
  languagesHeading: "Languages",
  attachmentsHeading: "Attachments",
  dragDropText: "Drag and drop attachments here, or",
  chooseFileText: "choose a file",
  attachmentEgText:
    "E.g. Resume, Professional Reference Letter, Experience Letter, etc.",
  maxSizeText: "Max size: 20MB",
  cancelBtn: "Cancel",
  applyBtn: "Apply",
  applyingText: "Applying...",
  footerCopyright: "© Copyright 2026 NestAssist",
  searchSkillsPlaceholder: "Search for skills...",
  noMatchingSkills: "No matching skills found",
  selectSkillsMessage:
    "Please select your skills & expertise first to see available services.",
  failedToFetchServiceTypes: "Failed to fetch service types:",
  failedToFetchCategories: "Failed to fetch categories:",
  unsupportedFormat: "is not a supported format (PDF, DOC, DOCX, PNG, JPG).",
  exceedsSizeLimit: "exceeds the 20 MB size limit.",
  labelFullName: "Full Name",
  labelDOB: "DOB",
  labelGender: "Gender",
  labelMobileNumber: "Mobile Number",
  labelEmail: "Email",
  labelApplyingFor: "Applying For",
  labelPermanentAddress: "Permanent Address",
  labelResidentialAddress: "Residential Address",
  labelSchoolCollege: "School/College",
  labelPassingYear: "Passing Year",
  labelTotalPercentage: "Marks",
  labelOrganizationName: "Company Name",
  labelJobRole: "Your Role",
  labelYearsExperience: "Years of Experience",
  labelCurrentlyWorking: "Currently working here",
  labelFrom: "From",
  labelTo: "To",
  labelLanguage: "Language",
  labelProficiency: "Proficiency",
  addBtn: "Add",
  requiredError: "Required",
};
