export const SERVICE_MANAGEMENT_TEXT = {
  editServiceTitle: "Edit Service",
  addServiceTitle: "Add Service",
  nameLabel: "Name*",
  subCategoryLabel: "Sub Category*",
  durationLabel: "Duration*",
  priceLabel: "Price*",
  commissionLabel: "Commission*",
  durationAddon: "min",
  priceAddon: "$",
  commissionAddon: "%",
  serviceImagesLabel: "Service Images",
  availabilityLabel: "Availability",
  serviceIncludesLabel: "Service Includes",
  serviceExcludesLabel: "Service Excludes",
  inclusionPointsLabel: "Inclusion Points",
  exclusionPointsLabel: "Exclusion Points",
  cancelBtn: "Cancel",
  saveBtn: "Save",
  updateBtn: "Update",
  loadingSubcategories: "Loading...",
  noSubcategories: "No subcategories available",
  tableId: "Id",
  tableName: "Name",
  tableSubCategory: "Sub Category",
  tablePrice: "Price",
  tableCommission: "Commission",
  tableAvailability: "Availability",
  createdBy: "Created By",
  tableAction: "Action",
  tableNoServices: "No services found.",
  enableServiceTitle: "Enable Service",
  disableServiceTitle: "Disable Service",
  confirmEnableDisableStart: "Are you sure you want to ",
  enableActionText: "enable",
  disableActionText: "disable",
  enableBtn: "Enable",
  disableBtn: "Disable",
  pageTitle: "Service Management",
  categoryGroups: "Category Groups",
  addCategoryGroup: "Add Category Group",
  failedToFetch: "Failed to fetch service types:",
  serviceUpdated: "Service type updated successfully!",
  serviceAdded: "Service type added successfully!",
  loadingServices: "Loading service types...",
  failedToFetchDetails: "Failed to fetch service details:",
  failedToLoadDetails: "Failed to load service details",
  serviceNotFound: "Service not found",
  goBack: "Go Back",
  editBtn: "Edit",
  serviceName: "Service Name",
  serviceType: "Service Type",
  serviceCategory: "Service Category",
  serviceSubCategory: "Service Sub Category",
  available: "Available",
  unavailable: "Unavailable",
  noImages: "No images uploaded",
  cleaningIncludes: "Cleaning Includes",
  cleaningExcludes: "Cleaning Excludes",
  noneListed: "None listed",
};
