export const USER_MANAGEMENT_TEXT = {
  customersPageTitle: "Customers",
  adminUsersPageTitle: "Admin Users",
  partnerPageTitle: "Partners",
  addBtn: "Add",
  filterTitle: "Filter",
  customerNameHeader: "Customer Name",
  mobileNumberHeader: "Mobile Number",
  emailHeader: "Email",
  pendingBookingsHeader: "Pending Bookings",
  totalBookingsHeader: "Total Bookings",
  statusHeader: "Status",
  actionHeader: "Action",
  idHeader: "ID",
  customerDeletedSuccess: "Customer deleted successfully",
  customerStatusUpdated: "Customer status updated to",
  failedToFetchCustomers: "Failed to fetch customers",
  errorFetchingCustomers: "Error fetching customers:",
  blockCustomerTitle: "Block Customer",
  unblockCustomerTitle: "Unblock Customer",
  blockMsg: "Are you sure you want to block",
  unblockMsg: "Are you sure you want to unblock",
  blockBtn: "Block",
  unblockBtn: "Unblock",
  deleteBtn: "Delete",
  areUSuretxt:"Are you sure you want to",
};
